### ISSUE TITLE
Why limit the buffer size with FRAME_MAX_LEN?

### ISSUE THREAD

**Issue by ArtemGr** [Xudong-Huang/conetty#1]
Regarding the `FRAME_MAX_LEN`, https://github.com/Xudong-Huang/conetty/blob/7acf95759db0093737001f6a1ad48b0ca419cf4c/src/frame.rs#L15

I'm getting the `len <= FRAME_MAX_LEN` assertion failure when trying to send a large piece of data with may_rpc. Why the limit?

(If this is by design then you should probably mention in may_rpc README that it can't be used for large messages; I can submit a PR for that if you want).

**Comment by Xudong-Huang** [comment]
Sorry I didn't aware the issue here. Yes, it's by design for security reasons. if a bad client try to attack the server, like give a huge data length, the server would try to alloc that amount memory and run into OOM.

**Comment by ArtemGr** [comment]
kk, thanks!
